# Generated by Django 5.2.4 on 2025-08-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='departament',
            new_name='department',
        ),
    ]
