# Generated by Django 5.2.4 on 2025-08-02 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название картриджа')),
                ('compatible_cartridge', models.CharField(max_length=100, verbose_name='Совместимый картридж')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Подключен к принтеру')),
                ('printer_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.printer', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
