# Generated by Django 5.2.4 on 2025-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_cartridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='is_disposed',
            field=models.BooleanField(default=False, verbose_name='Отправлен в утиль'),
        ),
    ]
