# Generated by Django 5.2.4 on 2025-08-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_cartridge_is_disposed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('movement_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Выбытие'), ('transfer', 'Перемещение')], max_length=20, verbose_name='Тип перемещения')),
                ('from_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Откуда')),
                ('to_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Куда')),
                ('date_moved', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.cartridge', verbose_name='Элемент')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем перемещено')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('location', models.CharField(max_length=50, verbose_name='Местоположение')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.cartridge', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Запас',
                'verbose_name_plural': 'Запасы',
            },
        ),
    ]
