# Generated by Django 5.2.4 on 2025-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_movement_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='item',
        ),
        migrations.AddField(
            model_name='movement',
            name='item_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID техники'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='item_type',
            field=models.CharField(choices=[('computer', 'Компьютер'), ('printer', 'Принтер')], default=1, max_length=20, verbose_name='Тип техники'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
