# Generated by Django 5.2.4 on 2025-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_movement_item_movement_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='is_disposed',
            field=models.BooleanField(default=False, verbose_name='Отправлено в утиль'),
        ),
    ]
